services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dfx-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - dfxnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dfx-frontend
    ports:
      - "5173:5173"
    networks:
      - dfxnet

networks:
  dfxnet:
